# Generated by Django 4.1.2 on 2022-10-29 20:31

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('naam', models.CharField(help_text='Naam van de boot', max_length=255, verbose_name='Naam')),
                ('model', models.CharField(blank=True, help_text='Model boot', max_length=255, verbose_name='Model')),
                ('toelichting', models.TextField(blank=True, help_text='Toelichting bij deze boot', verbose_name='Toelichting')),
                ('gph', models.FloatField(blank=True, help_text='GPH van deze boot', null=True, verbose_name='GPH')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', unique=True)),
            ],
            options={
                'verbose_name': 'boot',
                'verbose_name_plural': 'boten',
                'ordering': ['naam'],
            },
        ),
        migrations.CreateModel(
            name='PolarpuntType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('type', models.CharField(max_length=100, verbose_name='Polarpunt Type')),
                ('beschrijving', models.TextField(blank=True, verbose_name='Beschrijving')),
                ('uuid', models.UUIDField(default=uuid.uuid4, help_text='Unique identifier (UUID4)', unique=True)),
            ],
            options={
                'verbose_name': 'polarpunt type',
                'verbose_name_plural': 'polarpunt types',
                'ordering': ['type'],
            },
        ),
        migrations.CreateModel(
            name='Polarpunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('windspeed', models.PositiveIntegerField(verbose_name='windspeed')),
                ('twa', models.FloatField(default=0, verbose_name='ware windhoek')),
                ('boatspeed', models.FloatField(blank=True, null=True, verbose_name='predicted boatspeed')),
                ('vmg', models.FloatField(blank=True, null=True, verbose_name='predicted VMG')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID4)', unique=True)),
                ('boot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polarpunten', to='boten.boot')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polarpunten', to='boten.polarpunttype')),
            ],
            options={
                'verbose_name': 'polarpunt',
                'verbose_name_plural': 'polarpunten',
            },
        ),
    ]
